In [1]:
# 1. Initialise anumby array of 5*5 dimensions with all the values to be 0
import numpy as np


In [5]:
arr1=np.zeros((5,5), dtype=int)

In [6]:
arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
np.full((5,5),0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
# 2. Create a numpy array with initial value 10 and final 100 with an interval of 5 between each value
arr2 = np.arange(10,101,5)

In [10]:
arr2

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [11]:
# 3. Create a2-D array with values (10,20,30,40,50,60) and set the dimension to be 2*3
arr3 = np.arange(10,61,10).reshape(2,3)

In [12]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
num3 = np.array([10,20,30,40,50,60]).reshape(2,3)

In [14]:
num3

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
# a.Print the number elements in the arrays
print(arr3)

[[10 20 30]
 [40 50 60]]


In [16]:
# b. Get the data type of the array
arr3.dtype

dtype('int32')

In [17]:
# 4. Create first numpy array with values(1,2,3). Create second numpy array with values (4,5,6). 
# Perform simple arithmatic operations on the two numpy arrays:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])


In [18]:
# a. Addition
a1+a2

array([5, 7, 9])

In [19]:
# b. Subtraction
a1-a2

array([-3, -3, -3])

In [20]:
# c. Multiplication
a1*a2

array([ 4, 10, 18])

In [21]:
# d. Division
a1/a2

array([0.25, 0.4 , 0.5 ])

In [26]:
#  np.add(),np.subtract(), np.multiply(). np.divide()

In [25]:
np.add(a1,a2)

array([5, 7, 9])

In [27]:
# 5. Create a numpy array with values 10-90 and set the shape to be 3*3
arr4=np.arange(10,91,10).reshape(3,3)

In [28]:
arr4

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [31]:
# a. Extract only 3rd column from the numpy array
arr4[:,[2]]

array([[30],
       [60],
       [90]])

In [38]:
# b. Extract only the 2nd row from the numpy array
arr4[1,:]

array([40, 50, 60])

In [39]:
# c. Extract those cells at the intersection of first two rows and first two columns
arr4[:2,:2]

array([[10, 20],
       [40, 50]])